### PR TITLE
Improvement

### PR DESCRIPTION
**Pull request by valenttegar**
Overall, i'm extended the functionality of the original CEF interface by adding methods related to managing focus, hiding the browser, and subscribing to events. Additionally, you defined interfaces for player data and HUD components to ensure type safety when using these interfaces within the CEF interface.

### CODE REVIEW

**Comment by Brownield** [comment]
Good commit 👍

**Comment by Hold404** [comment]
I wrote types, becouse samp cef plugin injectjs those properties to the window object, but in ts we can't access them, before typing or defining. I'm not sure, that fields, you've defined are provided in window object by samp-cef.

**Comment by valenttegar** [comment]
I've included links to the original sources for reference.

readonly 'game:data:playerStats': string;
readonly 'game:hud:newVisibleState': string;
readonly 'game:data:pollPlayerStats': string;
readonly 'game:hud:setComponentVisible': string;

This setup facilitates autocomplete functionality in vscode or other IDEs, offering convenience for those who prefer not to delve into the documentation or source material

Screenshot_20240528_120843

**Comment by Brownield** [comment]
It's not bad, it's even good that a helper has appeared

**Comment by Hold404** [comment]
Okay, good improvments, thanks.

**Pull request merged**
